export const routes = [
  // --- Active Users ---
  {
    path: "/active-users-dashboard",
    label: "Dashboard",
    icon: "Activity",
    showInSidebar: true,
    group: "Active Users",
    groupIcon: "Activity",
    groupOrder: -1,
    order: 1,
    permission: "active_users.view",
  },
  {
    path: "/active-users-list",
    label: "Users List",
    icon: "Users",
    showInSidebar: true,
    group: "Active Users",
    groupIcon: "Activity",
    groupOrder: -1,
    order: 2,
    permission: "active_users.view",
  },
  {
    path: "/live-users",
    label: "Live Now",
    icon: "Zap",
    showInSidebar: true,
    group: "Active Users",
    groupIcon: "Activity",
    groupOrder: -1,
    order: 3,
    permission: "active_users.view",
  },
  {
    path: "/funnel-analytics",
    label: "Funnel Analytics",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "Active Users",
    groupIcon: "Activity",
    groupOrder: -1,
    order: 4,
    permission: "active_users.view",
  },

  // --- Executive Dashboards ---
  // {
  //   path: "/executive-dashboard",
  //   label: "Overview",
  //   icon: "LayoutDashboard",
  //   showInSidebar: true,
  //   group: "Executive",
  //   groupIcon: "LayoutDashboard",
  //   groupOrder: 0,
  //   order: 1,
  //   permission: "executive_dashboard.view",
  // },
  // {
  //   path: "/lender-management-pro",
  //   label: "Lender Performance",
  //   icon: "Target",
  //   showInSidebar: true,
  //   group: "Executive",
  //   groupIcon: "LayoutDashboard",
  //   groupOrder: 0,
  //   order: 2,
  //   permission: "executive_dashboard.view",
  // },
  // {
  //   path: "/app-statistics-pro",
  //   label: "App Statistics Pro",
  //   icon: "Smartphone",
  //   showInSidebar: true,
  //   group: "Executive",
  //   groupIcon: "LayoutDashboard",
  //   groupOrder: 0,
  //   order: 3,
  //   permission: "executive_dashboard.view",
  // },
  // {
  //   path: "/mutual-funds-dashboard",
  //   label: "MF Dashboard",
  //   icon: "TrendingUp",
  //   showInSidebar: true,
  //   group: "Executive",
  //   groupIcon: "LayoutDashboard",
  //   groupOrder: 0,
  //   order: 4,
  //   permission: "executive_dashboard.view",
  // },
  {
    path: "/internal-mf-dashboard",
    label: "Internal MF Pro",
    icon: "PieChart",
    showInSidebar: false,
    group: "Executive",
    groupIcon: "LayoutDashboard",
    groupOrder: 0,
    order: 5,
    permission: "executive_dashboard.view",
  },

  // --- Dashboard ---
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    permission: null,
  },

  // --- Lead Management ---
  {
    path: "/signin-user",
    label: "App Leads",
    icon: "Smartphone",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 1,
    permission: "lead_management.view",
  },
  {
    path: "/leads",
    label: "Web Leads",
    icon: "Globe",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 2,
    permission: "lead_management.view",
  },
  {
    path: "/partner-leads",
    label: "UTM Leads",
    icon: "Link",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 3,
    permission: "lead_management.view",
  },
  {
    path: "/all-leads",
    label: "All Leads",
    icon: "Users",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 4,
    permission: "lead_management.view",
  },
  {
    path: "/gold-loan-leads",
    label: "Gold Loan Leads",
    icon: "BadgePercent",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 5,
    permission: "lead_management.view",
  },
  {
    path: "/archive-users",
    label: "Archived",
    icon: "Archive",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 5,
    permission: "lead_management.delete",
  },
  {
    path: "/contact",
    label: "Contact Requests",
    icon: "MessageCircle",
    showInSidebar: true,
    group: "Lead Management",
    groupIcon: "Users",
    groupOrder: 1,
    order: 6,
    permission: "lead_management.view",
  },

  // --- App Statistics ---
  {
    path: "/app-metrics",
    label: "View Metrics",
    icon: "BarChart2",
    showInSidebar: true,
    group: "App Statistics",
    groupIcon: "BarChart2",
    groupOrder: 2,
    order: 1,
    permission: "app_statistics.view",
  },
  {
    path: "/upload-app-metrics",
    label: "Upload Data",
    icon: "Upload",
    showInSidebar: true,
    group: "App Statistics",
    groupIcon: "BarChart2",
    groupOrder: 2,
    order: 2,
    permission: "app_statistics.create",
  },

  // --- Analytics ---
  {
    path: "/analytics-dashboard",
    label: "Dashboard",
    icon: "LineChart",
    showInSidebar: true,
    group: "Analytics",
    groupIcon: "LineChart",
    groupOrder: 3,
    order: 1,
    permission: "analytics.view",
  },

  // --- Internal Mutual Funds ---
  {
    path: "/internal-mf",
    label: "MF Details",
    icon: "Wallet",
    showInSidebar: true,
    group: "Internal Mutual Funds",
    groupIcon: "Wallet",
    groupOrder: 4,
    order: 1,
    permission: "internal_mutual_funds.view",
  },

  // --- Mutual Funds ---
  {
    path: "/fetch-mf-loans-summary",
    label: "Loans Summary",
    icon: "FileText",
    showInSidebar: true,
    group: "Mutual Funds",
    groupIcon: "DollarSign",
    groupOrder: 5,
    order: 1,
    permission: "mutual_funds.view",
  },
  {
    path: "/fetch-all-mf-users",
    label: "All Users",
    icon: "Users",
    showInSidebar: true,
    group: "Mutual Funds",
    groupIcon: "DollarSign",
    groupOrder: 5,
    order: 2,
    permission: "mutual_funds.view",
  },
  {
    path: "/fetch-all-mf-loans",
    label: "All Loans",
    icon: "CreditCard",
    showInSidebar: true,
    group: "Mutual Funds",
    groupIcon: "DollarSign",
    groupOrder: 5,
    order: 3,
    permission: "mutual_funds.view",
  },

  // --- Lender Management ---
  {
    path: "/list-of-lenders",
    label: "All Lenders",
    icon: "Building2",
    showInSidebar: true,
    group: "Lender Management",
    groupIcon: "Building2",
    groupOrder: 6,
    order: 1,
    permission: "lender_management.view",
  },
  {
    path: "/on-borde-lender-from",
    label: "Onboard New",
    icon: "UserPlus",
    showInSidebar: true,
    group: "Lender Management",
    groupIcon: "Building2",
    groupOrder: 6,
    order: 2,
    permission: "lender_management.create",
  },

  // --- Blogs ---
  {
    path: "/blogs",
    label: "All Blogs",
    icon: "FileText",
    showInSidebar: true,
    order: 1,
    group: "Blogs",
    groupIcon: "BookOpen",
    groupOrder: 7,
    permission: "blogs.view",
  },
  {
    path: "/blog/create",
    label: "Create New",
    icon: "PenTool",
    showInSidebar: true,
    order: 2,
    group: "Blogs",
    groupIcon: "BookOpen",
    groupOrder: 7,
    permission: "blogs.create",
  },

  // --- Push Notification ---
  {
    path: "/group",
    label: "Groups",
    icon: "Users",
    showInSidebar: true,
    group: "Push Notification",
    groupIcon: "Bell",
    groupOrder: 8,
    order: 1,
    permission: "push_notification.view",
  },
  {
    path: "/push-notification",
    label: "Templates",
    icon: "Send",
    showInSidebar: true,
    group: "Push Notification",
    groupIcon: "Bell",
    groupOrder: 8,
    order: 2,
    permission: "push_notification.view",
  },

  // --- UTM ---
  {
    path: "/utm-generate",
    label: "Generate UTM",
    icon: "Link2",
    showInSidebar: true,
    group: "UTM",
    groupIcon: "Link2",
    groupOrder: 9,
    order: 1,
    permission: "utm.view",
  },

  // --- FAQ ---
  {
    path: "/faq",
    label: "Manage FAQs",
    icon: "HelpCircle",
    showInSidebar: true,
    order: 1,
    group: "FAQ",
    groupIcon: "HelpCircle",
    groupOrder: 10,
    permission: "faq.view",
  },

  // --- MIS Raw ---
  {
    path: "/mis-zype-data",
    label: "View Data",
    icon: "Database",
    showInSidebar: true,
    group: "MIS Raw",
    groupIcon: "Database",
    groupOrder: 11,
    order: 1,
    permission: "mis_raw.view",
  },

  // --- CMS Management ---
  {
    path: "/press",
    label: "Press Room",
    icon: "Newspaper",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 1,
    permission: "cms_management.view",
  },
  {
    path: "/testimonials",
    label: "Testimonials",
    icon: "Quote",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 2,
    permission: "cms_management.view",
  },
  {
    path: "/banners",
    label: "Banners",
    icon: "Image",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 3,
    permission: "cms_management.view",
  },
  {
    path: "/terms-conditions",
    label: "Pages",
    icon: "FileText",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 4,
    permission: "cms_management.edit",
  },

  {
    path: "/credit-cards",
    label: "Credit Cards",
    icon: "CreditCard",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 5,
    permission: "cms_management.view",
  },
  {
    path: "/credit-card-clicks",
    label: "Card Clicks",
    icon: "MousePointerClick",
    showInSidebar: true,
    group: "CMS Management",
    groupIcon: "Settings",
    groupOrder: 12,
    order: 6,
    permission: "cms_management.view",
  },

  // --- Admin Management ---
  {
    path: "/admin/roles",
    label: "Roles",
    icon: "Shield",
    showInSidebar: true,
    group: "Admin Management",
    groupIcon: "Shield",
    groupOrder: 99,
    order: 1,
    permission: "admin_management.view",
  },
  {
    path: "/admin/users",
    label: "Admin Users",
    icon: "UserCog",
    showInSidebar: true,
    group: "Admin Management",
    groupIcon: "Shield",
    groupOrder: 99,
    order: 2,
    permission: "admin_management.view",
  },
  {
    path: "/admin/roles/:id/edit",
    label: "Edit Role",
    icon: "Shield",
    showInSidebar: false,
    group: "Admin Management",
    groupIcon: "Shield",
    groupOrder: 99,
    order: 3,
    permission: "admin_management.edit",
  },
];
