export const routes = [
  // --- Active Users ---
  {
    path: "/active-users-dashboard",
    label: "Active Users Stats",
    icon: "Activity",
    showInSidebar: true,
    group: "Active Users",
    groupOrder: -1,
    order: 1,
    permission: "active_users.view",
  },
  {
    path: "/active-users-list",
    label: "Active Users List",
    icon: "Users",
    showInSidebar: true,
    group: "Active Users",
    groupOrder: -1,
    order: 2,
    permission: "active_users.view",
  },
  {
    path: "/live-users",
    label: "Live Users",
    icon: "Activity",
    showInSidebar: true,
    group: "Active Users",
    groupOrder: -1,
    order: 3,
    permission: "active_users.view",
  },
  {
    path: "/funnel-analytics",
    label: "Funnel Analytics",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "Active Users",
    groupOrder: -1,
    order: 4,
    permission: "active_users.view",
  },

  // --- Executive Dashboards (Founder) ---
  {
    path: "/executive-dashboard",
    label: "Executive Overview",
    icon: "LayoutDashboard",
    showInSidebar: true,
    group: "Executive",
    groupOrder: 0,
    order: 1,
    permission: "executive_dashboard.view",
  },
  {
    path: "/lender-management-pro",
    label: "Lender Performance",
    icon: "Target",
    showInSidebar: true,
    group: "Executive",
    groupOrder: 0,
    order: 2,
    permission: "executive_dashboard.view",
  },
  {
    path: "/app-statistics-pro",
    label: "App Statistics Pro",
    icon: "Smartphone",
    showInSidebar: true,
    group: "Executive",
    groupOrder: 0,
    order: 3,
    permission: "executive_dashboard.view",
  },
  {
    path: "/mutual-funds-dashboard",
    label: "MF Dashboard",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "Executive",
    groupOrder: 0,
    order: 4,
    permission: "executive_dashboard.view",
  },
  {
    path: "/internal-mf-dashboard",
    label: "Internal MF Pro",
    icon: "PieChart",
    showInSidebar: true,
    group: "Executive",
    groupOrder: 0,
    order: 5,
    permission: "executive_dashboard.view",
  },

  // --- Non-grouped (Dashboard) ---
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    permission: null, // Everyone can access dashboard
  },

  // --- Lead Management ---
  {
    path: "/signin-user",
    label: "App Leads",
    icon: "LucideMonitor",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 1,
    permission: "lead_management.view",
  },
  {
    path: "/leads",
    label: "Web Leads",
    icon: "Users",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 2,
    permission: "lead_management.view",
  },
  {
    path: "/partner-leads",
    label: "UTM Leads",
    icon: "Users",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 3,
    permission: "lead_management.view",
  },
  {
    path: "/all-leads",
    label: "All Leads",
    icon: "Users2",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 4,
    permission: "lead_management.view",
  },
  {
    path: "/archive-users",
    label: "Archive users",
    icon: "UserMinus",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 5,
    permission: "lead_management.delete",
  },
  {
    path: "/contact",
    label: "Contact US",
    icon: "Phone",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 6,
    permission: "lead_management.view",
  },

  // --- App Statistics ---
  {
    path: "/app-metrics",
    label: "App Metrics",
    icon: "Camera",
    showInSidebar: true,
    group: "App Statistics",
    groupOrder: 2,
    order: 1,
    permission: "app_statistics.view",
  },
  {
    path: "/upload-app-metrics",
    label: "Upload File",
    icon: "Upload",
    showInSidebar: true,
    group: "App Statistics",
    groupOrder: 2,
    order: 2,
    permission: "app_statistics.create",
  },

  // --- Analytics ---
  {
    path: "/analytics-dashboard",
    label: "Analytics Dashboard",
    icon: "LineChart",
    showInSidebar: true,
    group: "Analytics",
    groupOrder: 3,
    order: 1,
    permission: "analytics.view",
  },

  // --- Internal Mutual Funds ---
  {
    path: "/internal-mf",
    label: "Internal MF Detail",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Internal Mutual Funds",
    groupOrder: 4,
    order: 1,
    permission: "internal_mutual_funds.view",
  },

  // --- Mutual Funds ---
  {
    path: "/fetch-mf-loans-summary",
    label: "Fetch Loans Summary",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Mutual Funds",
    groupOrder: 5,
    order: 1,
    permission: "mutual_funds.view",
  },
  {
    path: "/fetch-all-mf-users",
    label: "Fetch All Users",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Mutual Funds",
    groupOrder: 5,
    order: 2,
    permission: "mutual_funds.view",
  },
  {
    path: "/fetch-all-mf-loans",
    label: "Fetch All Loans",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Mutual Funds",
    groupOrder: 5,
    order: 3,
    permission: "mutual_funds.view",
  },

  // --- Lender Management ---
  {
    path: "/list-of-lenders",
    label: "List of Lenders",
    icon: "Building2",
    showInSidebar: true,
    group: "Lender Management",
    groupOrder: 6,
    order: 1,
    permission: "lender_management.view",
  },
  {
    path: "/on-borde-lender-from",
    label: "Onboard Lender",
    icon: "UserPlus",
    showInSidebar: true,
    group: "Lender Management",
    groupOrder: 6,
    order: 2,
    permission: "lender_management.create",
  },

  // --- Blogs ---
  {
    path: "/blogs",
    label: "Blogs View",
    icon: "FileText",
    showInSidebar: true,
    order: 1,
    group: "Blogs",
    groupOrder: 7,
    permission: "blogs.view",
  },
  {
    path: "/blog/create",
    label: "Blog Create",
    icon: "BookOpen",
    showInSidebar: true,
    order: 2,
    group: "Blogs",
    groupOrder: 7,
    permission: "blogs.create",
  },

  // --- Push Notification ---
  {
    path: "/group",
    label: "Groups",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Push Notification",
    groupOrder: 8,
    order: 1,
    permission: "push_notification.view",
  },
  {
    path: "/push-notification",
    label: "Push Notification",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Push Notification",
    groupOrder: 8,
    order: 2,
    permission: "push_notification.view",
  },

  // --- UTM ---
  {
    path: "/utm-generate",
    label: "UTM Generate",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "UTM",
    groupOrder: 9,
    order: 1,
    permission: "utm.view",
  },

  // --- FAQ ---
  {
    path: "/faq",
    label: "FAQ View",
    icon: "HelpCircle",
    showInSidebar: true,
    order: 1,
    group: "FAQ",
    groupOrder: 10,
    permission: "faq.view",
  },

  // --- MIS Raw ---
  {
    path: "/mis-zype-data",
    label: "MIS Data",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "MIS Raw",
    groupOrder: 11,
    order: 1,
    permission: "mis_raw.view",
  },

  // --- CMS Management ---
  {
    path: "/press",
    label: "Press Room",
    icon: "Newspaper",
    showInSidebar: true,
    group: "CMS Management",
    groupOrder: 12,
    order: 1,
    permission: "cms_management.view",
  },
  {
    path: "/testimonials",
    label: "Testimonials",
    icon: "MessageSquare",
    showInSidebar: true,
    group: "CMS Management",
    groupOrder: 12,
    order: 2,
    permission: "cms_management.view",
  },
  {
    path: "/banners",
    label: "Banners",
    icon: "FileText",
    showInSidebar: true,
    group: "CMS Management",
    groupOrder: 12,
    order: 3,
    permission: "cms_management.view",
  },
  {
    path: "/terms-conditions",
    label: "Pages",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "CMS Management",
    groupOrder: 12,
    order: 4,
    permission: "cms_management.edit",
  },

  // --- Admin Management ---
  {
    path: "/admin/roles",
    label: "Roles",
    icon: "Shield",
    showInSidebar: true,
    group: "Admin Management",
    groupOrder: 99,
    order: 1,
    permission: "admin_management.view",
  },
  {
    path: "/admin/users",
    label: "Admin Users",
    icon: "UserCog",
    showInSidebar: true,
    group: "Admin Management",
    groupOrder: 99,
    order: 2,
    permission: "admin_management.view",
  },
  {
    path: "/admin/roles/:id/edit",
    label: "Edit Role",
    icon: "Shield",
    showInSidebar: false,
    group: "Admin Management",
    groupOrder: 99,
    order: 3,
    permission: "admin_management.edit",
  },
];
